# Generated by Django 4.2.7 on 2023-12-02 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Details', '0001_initial'),
        ('Professional_Details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalEventAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event_Details.eventdetails')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Professional_Details.professional')),
            ],
        ),
    ]
