# Generated by Django 4.2.7 on 2023-12-04 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Health_Institutions', '0002_healthinstitution_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthinstitution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
