# Generated by Django 4.2.7 on 2023-12-02 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Details', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventdetails',
            old_name='address',
            new_name='cotact_person',
        ),
    ]
